[package]
  name = "uptime-monitor"
  version = "0.1.0"
  edition = "2021"
  publish = false

[dependencies]
  tokio = { version = "1", features = ["macros"] }
  serde = { version = "1", features = ["derive"] }
  serde_json = { version = "1", features = ["raw_value"] }
  serde_derive = "1"
  vercel_runtime = { version = "1" }

[lib]
  path = "lib/lib.rs"

[[bin]]
  name = "hello"
  path = "api/hello.rs"
